package com.escom.schoolsaes.dao;

import com.escom.schoolsaes.model.Alumno;
import com.escom.schoolsaes.model.AlumnoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlumnoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int countByExample(AlumnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByExample(AlumnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insert(Alumno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insertSelective(Alumno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    List<Alumno> selectByExample(AlumnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    Alumno selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Alumno record, @Param("example") AlumnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExample(@Param("record") Alumno record, @Param("example") AlumnoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKeySelective(Alumno record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKey(Alumno record);
}