package com.escom.schoolsaes.dao;

import com.escom.schoolsaes.model.Calificacion;
import com.escom.schoolsaes.model.CalificacionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CalificacionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int countByExample(CalificacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByExample(CalificacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insert(Calificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insertSelective(Calificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    List<Calificacion> selectByExample(CalificacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    Calificacion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Calificacion record, @Param("example") CalificacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExample(@Param("record") Calificacion record, @Param("example") CalificacionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKeySelective(Calificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKey(Calificacion record);
}