package com.escom.schoolsaes.dao;

import com.escom.schoolsaes.model.CarreraInstitucion;
import com.escom.schoolsaes.model.CarreraInstitucionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarreraInstitucionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera_institucion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int countByExample(CarreraInstitucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera_institucion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByExample(CarreraInstitucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera_institucion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera_institucion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insert(CarreraInstitucion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera_institucion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insertSelective(CarreraInstitucion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera_institucion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    List<CarreraInstitucion> selectByExample(CarreraInstitucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera_institucion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    CarreraInstitucion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera_institucion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExampleSelective(@Param("record") CarreraInstitucion record, @Param("example") CarreraInstitucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera_institucion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExample(@Param("record") CarreraInstitucion record, @Param("example") CarreraInstitucionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera_institucion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKeySelective(CarreraInstitucion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera_institucion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKey(CarreraInstitucion record);
}