package com.escom.schoolsaes.dao;

import com.escom.schoolsaes.model.Carrera;
import com.escom.schoolsaes.model.CarreraExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarreraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int countByExample(CarreraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByExample(CarreraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insert(Carrera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insertSelective(Carrera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    List<Carrera> selectByExample(CarreraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    Carrera selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Carrera record, @Param("example") CarreraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExample(@Param("record") Carrera record, @Param("example") CarreraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKeySelective(Carrera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKey(Carrera record);
}