package com.escom.schoolsaes.dao;

import com.escom.schoolsaes.model.Centroestudios;
import com.escom.schoolsaes.model.CentroestudiosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CentroestudiosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int countByExample(CentroestudiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByExample(CentroestudiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insert(Centroestudios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insertSelective(Centroestudios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    List<Centroestudios> selectByExample(CentroestudiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    Centroestudios selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Centroestudios record, @Param("example") CentroestudiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExample(@Param("record") Centroestudios record, @Param("example") CentroestudiosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKeySelective(Centroestudios record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKey(Centroestudios record);
}