package com.escom.schoolsaes.dao;

import com.escom.schoolsaes.model.Examen;
import com.escom.schoolsaes.model.ExamenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExamenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int countByExample(ExamenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByExample(ExamenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insert(Examen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insertSelective(Examen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    List<Examen> selectByExample(ExamenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    Examen selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Examen record, @Param("example") ExamenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExample(@Param("record") Examen record, @Param("example") ExamenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKeySelective(Examen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKey(Examen record);
}