package com.escom.schoolsaes.dao;

import com.escom.schoolsaes.model.Materia;
import com.escom.schoolsaes.model.MateriaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MateriaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materia
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int countByExample(MateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materia
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByExample(MateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materia
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materia
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insert(Materia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materia
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insertSelective(Materia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materia
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    List<Materia> selectByExample(MateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materia
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    Materia selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materia
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Materia record, @Param("example") MateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materia
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExample(@Param("record") Materia record, @Param("example") MateriaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materia
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKeySelective(Materia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table materia
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKey(Materia record);
}