package com.escom.schoolsaes.dao;

import com.escom.schoolsaes.model.Pregunta;
import com.escom.schoolsaes.model.PreguntaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreguntaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int countByExample(PreguntaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByExample(PreguntaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insert(Pregunta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insertSelective(Pregunta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    List<Pregunta> selectByExample(PreguntaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    Pregunta selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Pregunta record, @Param("example") PreguntaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExample(@Param("record") Pregunta record, @Param("example") PreguntaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKeySelective(Pregunta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKey(Pregunta record);
}