package com.escom.schoolsaes.dao;

import com.escom.schoolsaes.model.Respuesta;
import com.escom.schoolsaes.model.RespuestaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RespuestaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int countByExample(RespuestaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByExample(RespuestaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insert(Respuesta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int insertSelective(Respuesta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    List<Respuesta> selectByExample(RespuestaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    Respuesta selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExampleSelective(@Param("record") Respuesta record, @Param("example") RespuestaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByExample(@Param("record") Respuesta record, @Param("example") RespuestaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKeySelective(Respuesta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    int updateByPrimaryKey(Respuesta record);
}