package com.escom.schoolsaes.model;

import java.util.ArrayList;
import java.util.List;

public class AlumnoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public AlumnoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBoletaIsNull() {
            addCriterion("boleta is null");
            return (Criteria) this;
        }

        public Criteria andBoletaIsNotNull() {
            addCriterion("boleta is not null");
            return (Criteria) this;
        }

        public Criteria andBoletaEqualTo(String value) {
            addCriterion("boleta =", value, "boleta");
            return (Criteria) this;
        }

        public Criteria andBoletaNotEqualTo(String value) {
            addCriterion("boleta <>", value, "boleta");
            return (Criteria) this;
        }

        public Criteria andBoletaGreaterThan(String value) {
            addCriterion("boleta >", value, "boleta");
            return (Criteria) this;
        }

        public Criteria andBoletaGreaterThanOrEqualTo(String value) {
            addCriterion("boleta >=", value, "boleta");
            return (Criteria) this;
        }

        public Criteria andBoletaLessThan(String value) {
            addCriterion("boleta <", value, "boleta");
            return (Criteria) this;
        }

        public Criteria andBoletaLessThanOrEqualTo(String value) {
            addCriterion("boleta <=", value, "boleta");
            return (Criteria) this;
        }

        public Criteria andBoletaLike(String value) {
            addCriterion("boleta like", value, "boleta");
            return (Criteria) this;
        }

        public Criteria andBoletaNotLike(String value) {
            addCriterion("boleta not like", value, "boleta");
            return (Criteria) this;
        }

        public Criteria andBoletaIn(List<String> values) {
            addCriterion("boleta in", values, "boleta");
            return (Criteria) this;
        }

        public Criteria andBoletaNotIn(List<String> values) {
            addCriterion("boleta not in", values, "boleta");
            return (Criteria) this;
        }

        public Criteria andBoletaBetween(String value1, String value2) {
            addCriterion("boleta between", value1, value2, "boleta");
            return (Criteria) this;
        }

        public Criteria andBoletaNotBetween(String value1, String value2) {
            addCriterion("boleta not between", value1, value2, "boleta");
            return (Criteria) this;
        }

        public Criteria andNombreIsNull() {
            addCriterion("nombre is null");
            return (Criteria) this;
        }

        public Criteria andNombreIsNotNull() {
            addCriterion("nombre is not null");
            return (Criteria) this;
        }

        public Criteria andNombreEqualTo(String value) {
            addCriterion("nombre =", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotEqualTo(String value) {
            addCriterion("nombre <>", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThan(String value) {
            addCriterion("nombre >", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreGreaterThanOrEqualTo(String value) {
            addCriterion("nombre >=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThan(String value) {
            addCriterion("nombre <", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLessThanOrEqualTo(String value) {
            addCriterion("nombre <=", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreLike(String value) {
            addCriterion("nombre like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotLike(String value) {
            addCriterion("nombre not like", value, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreIn(List<String> values) {
            addCriterion("nombre in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotIn(List<String> values) {
            addCriterion("nombre not in", values, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreBetween(String value1, String value2) {
            addCriterion("nombre between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andNombreNotBetween(String value1, String value2) {
            addCriterion("nombre not between", value1, value2, "nombre");
            return (Criteria) this;
        }

        public Criteria andAppatIsNull() {
            addCriterion("appat is null");
            return (Criteria) this;
        }

        public Criteria andAppatIsNotNull() {
            addCriterion("appat is not null");
            return (Criteria) this;
        }

        public Criteria andAppatEqualTo(String value) {
            addCriterion("appat =", value, "appat");
            return (Criteria) this;
        }

        public Criteria andAppatNotEqualTo(String value) {
            addCriterion("appat <>", value, "appat");
            return (Criteria) this;
        }

        public Criteria andAppatGreaterThan(String value) {
            addCriterion("appat >", value, "appat");
            return (Criteria) this;
        }

        public Criteria andAppatGreaterThanOrEqualTo(String value) {
            addCriterion("appat >=", value, "appat");
            return (Criteria) this;
        }

        public Criteria andAppatLessThan(String value) {
            addCriterion("appat <", value, "appat");
            return (Criteria) this;
        }

        public Criteria andAppatLessThanOrEqualTo(String value) {
            addCriterion("appat <=", value, "appat");
            return (Criteria) this;
        }

        public Criteria andAppatLike(String value) {
            addCriterion("appat like", value, "appat");
            return (Criteria) this;
        }

        public Criteria andAppatNotLike(String value) {
            addCriterion("appat not like", value, "appat");
            return (Criteria) this;
        }

        public Criteria andAppatIn(List<String> values) {
            addCriterion("appat in", values, "appat");
            return (Criteria) this;
        }

        public Criteria andAppatNotIn(List<String> values) {
            addCriterion("appat not in", values, "appat");
            return (Criteria) this;
        }

        public Criteria andAppatBetween(String value1, String value2) {
            addCriterion("appat between", value1, value2, "appat");
            return (Criteria) this;
        }

        public Criteria andAppatNotBetween(String value1, String value2) {
            addCriterion("appat not between", value1, value2, "appat");
            return (Criteria) this;
        }

        public Criteria andApmatIsNull() {
            addCriterion("apmat is null");
            return (Criteria) this;
        }

        public Criteria andApmatIsNotNull() {
            addCriterion("apmat is not null");
            return (Criteria) this;
        }

        public Criteria andApmatEqualTo(String value) {
            addCriterion("apmat =", value, "apmat");
            return (Criteria) this;
        }

        public Criteria andApmatNotEqualTo(String value) {
            addCriterion("apmat <>", value, "apmat");
            return (Criteria) this;
        }

        public Criteria andApmatGreaterThan(String value) {
            addCriterion("apmat >", value, "apmat");
            return (Criteria) this;
        }

        public Criteria andApmatGreaterThanOrEqualTo(String value) {
            addCriterion("apmat >=", value, "apmat");
            return (Criteria) this;
        }

        public Criteria andApmatLessThan(String value) {
            addCriterion("apmat <", value, "apmat");
            return (Criteria) this;
        }

        public Criteria andApmatLessThanOrEqualTo(String value) {
            addCriterion("apmat <=", value, "apmat");
            return (Criteria) this;
        }

        public Criteria andApmatLike(String value) {
            addCriterion("apmat like", value, "apmat");
            return (Criteria) this;
        }

        public Criteria andApmatNotLike(String value) {
            addCriterion("apmat not like", value, "apmat");
            return (Criteria) this;
        }

        public Criteria andApmatIn(List<String> values) {
            addCriterion("apmat in", values, "apmat");
            return (Criteria) this;
        }

        public Criteria andApmatNotIn(List<String> values) {
            addCriterion("apmat not in", values, "apmat");
            return (Criteria) this;
        }

        public Criteria andApmatBetween(String value1, String value2) {
            addCriterion("apmat between", value1, value2, "apmat");
            return (Criteria) this;
        }

        public Criteria andApmatNotBetween(String value1, String value2) {
            addCriterion("apmat not between", value1, value2, "apmat");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andTelefonoIsNull() {
            addCriterion("telefono is null");
            return (Criteria) this;
        }

        public Criteria andTelefonoIsNotNull() {
            addCriterion("telefono is not null");
            return (Criteria) this;
        }

        public Criteria andTelefonoEqualTo(String value) {
            addCriterion("telefono =", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotEqualTo(String value) {
            addCriterion("telefono <>", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoGreaterThan(String value) {
            addCriterion("telefono >", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoGreaterThanOrEqualTo(String value) {
            addCriterion("telefono >=", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLessThan(String value) {
            addCriterion("telefono <", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLessThanOrEqualTo(String value) {
            addCriterion("telefono <=", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLike(String value) {
            addCriterion("telefono like", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotLike(String value) {
            addCriterion("telefono not like", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoIn(List<String> values) {
            addCriterion("telefono in", values, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotIn(List<String> values) {
            addCriterion("telefono not in", values, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoBetween(String value1, String value2) {
            addCriterion("telefono between", value1, value2, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotBetween(String value1, String value2) {
            addCriterion("telefono not between", value1, value2, "telefono");
            return (Criteria) this;
        }

        public Criteria andId_carreraIsNull() {
            addCriterion("id_carrera is null");
            return (Criteria) this;
        }

        public Criteria andId_carreraIsNotNull() {
            addCriterion("id_carrera is not null");
            return (Criteria) this;
        }

        public Criteria andId_carreraEqualTo(Integer value) {
            addCriterion("id_carrera =", value, "id_carrera");
            return (Criteria) this;
        }

        public Criteria andId_carreraNotEqualTo(Integer value) {
            addCriterion("id_carrera <>", value, "id_carrera");
            return (Criteria) this;
        }

        public Criteria andId_carreraGreaterThan(Integer value) {
            addCriterion("id_carrera >", value, "id_carrera");
            return (Criteria) this;
        }

        public Criteria andId_carreraGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_carrera >=", value, "id_carrera");
            return (Criteria) this;
        }

        public Criteria andId_carreraLessThan(Integer value) {
            addCriterion("id_carrera <", value, "id_carrera");
            return (Criteria) this;
        }

        public Criteria andId_carreraLessThanOrEqualTo(Integer value) {
            addCriterion("id_carrera <=", value, "id_carrera");
            return (Criteria) this;
        }

        public Criteria andId_carreraIn(List<Integer> values) {
            addCriterion("id_carrera in", values, "id_carrera");
            return (Criteria) this;
        }

        public Criteria andId_carreraNotIn(List<Integer> values) {
            addCriterion("id_carrera not in", values, "id_carrera");
            return (Criteria) this;
        }

        public Criteria andId_carreraBetween(Integer value1, Integer value2) {
            addCriterion("id_carrera between", value1, value2, "id_carrera");
            return (Criteria) this;
        }

        public Criteria andId_carreraNotBetween(Integer value1, Integer value2) {
            addCriterion("id_carrera not between", value1, value2, "id_carrera");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alumno
     *
     * @mbggenerated do_not_delete_during_merge Thu May 26 13:30:53 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}