package com.escom.schoolsaes.model;

public class Alumno {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumno.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumno.boleta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private String boleta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumno.nombre
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private String nombre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumno.appat
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private String appat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumno.apmat
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private String apmat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumno.email
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumno.telefono
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private String telefono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumno.id_carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id_carrera;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumno.id
     *
     * @return the value of alumno.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumno.id
     *
     * @param id the value for alumno.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumno.boleta
     *
     * @return the value of alumno.boleta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public String getBoleta() {
        return boleta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumno.boleta
     *
     * @param boleta the value for alumno.boleta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setBoleta(String boleta) {
        this.boleta = boleta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumno.nombre
     *
     * @return the value of alumno.nombre
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumno.nombre
     *
     * @param nombre the value for alumno.nombre
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumno.appat
     *
     * @return the value of alumno.appat
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public String getAppat() {
        return appat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumno.appat
     *
     * @param appat the value for alumno.appat
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setAppat(String appat) {
        this.appat = appat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumno.apmat
     *
     * @return the value of alumno.apmat
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public String getApmat() {
        return apmat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumno.apmat
     *
     * @param apmat the value for alumno.apmat
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setApmat(String apmat) {
        this.apmat = apmat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumno.email
     *
     * @return the value of alumno.email
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumno.email
     *
     * @param email the value for alumno.email
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumno.telefono
     *
     * @return the value of alumno.telefono
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumno.telefono
     *
     * @param telefono the value for alumno.telefono
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumno.id_carrera
     *
     * @return the value of alumno.id_carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId_carrera() {
        return id_carrera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumno.id_carrera
     *
     * @param id_carrera the value for alumno.id_carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId_carrera(Integer id_carrera) {
        this.id_carrera = id_carrera;
    }
}