package com.escom.schoolsaes.model;

public class CalificacionAlumno {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calificacion_alumno.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calificacion_alumno.id_examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id_examen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calificacion_alumno.id_calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id_calificacion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calificacion_alumno.boleta_alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer boleta_alumno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calificacion_alumno.id
     *
     * @return the value of calificacion_alumno.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calificacion_alumno.id
     *
     * @param id the value for calificacion_alumno.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calificacion_alumno.id_examen
     *
     * @return the value of calificacion_alumno.id_examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId_examen() {
        return id_examen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calificacion_alumno.id_examen
     *
     * @param id_examen the value for calificacion_alumno.id_examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId_examen(Integer id_examen) {
        this.id_examen = id_examen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calificacion_alumno.id_calificacion
     *
     * @return the value of calificacion_alumno.id_calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId_calificacion() {
        return id_calificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calificacion_alumno.id_calificacion
     *
     * @param id_calificacion the value for calificacion_alumno.id_calificacion
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId_calificacion(Integer id_calificacion) {
        this.id_calificacion = id_calificacion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calificacion_alumno.boleta_alumno
     *
     * @return the value of calificacion_alumno.boleta_alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getBoleta_alumno() {
        return boleta_alumno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calificacion_alumno.boleta_alumno
     *
     * @param boleta_alumno the value for calificacion_alumno.boleta_alumno
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setBoleta_alumno(Integer boleta_alumno) {
        this.boleta_alumno = boleta_alumno;
    }
}