package com.escom.schoolsaes.model;

public class Calificacion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calificacion.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calificacion.valor
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Float valor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calificacion.id
     *
     * @return the value of calificacion.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calificacion.id
     *
     * @param id the value for calificacion.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calificacion.valor
     *
     * @return the value of calificacion.valor
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Float getValor() {
        return valor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calificacion.valor
     *
     * @param valor the value for calificacion.valor
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setValor(Float valor) {
        this.valor = valor;
    }
}