package com.escom.schoolsaes.model;

public class CarreraInstitucion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carrera_institucion.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carrera_institucion.id_centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id_centroestudios;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carrera_institucion.id_Carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id_Carrera;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carrera_institucion.id
     *
     * @return the value of carrera_institucion.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carrera_institucion.id
     *
     * @param id the value for carrera_institucion.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carrera_institucion.id_centroestudios
     *
     * @return the value of carrera_institucion.id_centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId_centroestudios() {
        return id_centroestudios;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carrera_institucion.id_centroestudios
     *
     * @param id_centroestudios the value for carrera_institucion.id_centroestudios
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId_centroestudios(Integer id_centroestudios) {
        this.id_centroestudios = id_centroestudios;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carrera_institucion.id_Carrera
     *
     * @return the value of carrera_institucion.id_Carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId_Carrera() {
        return id_Carrera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carrera_institucion.id_Carrera
     *
     * @param id_Carrera the value for carrera_institucion.id_Carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId_Carrera(Integer id_Carrera) {
        this.id_Carrera = id_Carrera;
    }
}