package com.escom.schoolsaes.model;

import java.util.Date;

public class Examen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examen.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examen.fecha
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Date fecha;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examen.id_parcial
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id_parcial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examen.id_Carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id_Carrera;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examen.id
     *
     * @return the value of examen.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examen.id
     *
     * @param id the value for examen.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examen.fecha
     *
     * @return the value of examen.fecha
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examen.fecha
     *
     * @param fecha the value for examen.fecha
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examen.id_parcial
     *
     * @return the value of examen.id_parcial
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId_parcial() {
        return id_parcial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examen.id_parcial
     *
     * @param id_parcial the value for examen.id_parcial
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId_parcial(Integer id_parcial) {
        this.id_parcial = id_parcial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examen.id_Carrera
     *
     * @return the value of examen.id_Carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId_Carrera() {
        return id_Carrera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examen.id_Carrera
     *
     * @param id_Carrera the value for examen.id_Carrera
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId_Carrera(Integer id_Carrera) {
        this.id_Carrera = id_Carrera;
    }
}