package com.escom.schoolsaes.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ExamenExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public ExamenExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFechaIsNull() {
            addCriterion("fecha is null");
            return (Criteria) this;
        }

        public Criteria andFechaIsNotNull() {
            addCriterion("fecha is not null");
            return (Criteria) this;
        }

        public Criteria andFechaEqualTo(Date value) {
            addCriterionForJDBCDate("fecha =", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotEqualTo(Date value) {
            addCriterionForJDBCDate("fecha <>", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThan(Date value) {
            addCriterionForJDBCDate("fecha >", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha >=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThan(Date value) {
            addCriterionForJDBCDate("fecha <", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("fecha <=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaIn(List<Date> values) {
            addCriterionForJDBCDate("fecha in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotIn(List<Date> values) {
            addCriterionForJDBCDate("fecha not in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha between", value1, value2, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("fecha not between", value1, value2, "fecha");
            return (Criteria) this;
        }

        public Criteria andId_parcialIsNull() {
            addCriterion("id_parcial is null");
            return (Criteria) this;
        }

        public Criteria andId_parcialIsNotNull() {
            addCriterion("id_parcial is not null");
            return (Criteria) this;
        }

        public Criteria andId_parcialEqualTo(Integer value) {
            addCriterion("id_parcial =", value, "id_parcial");
            return (Criteria) this;
        }

        public Criteria andId_parcialNotEqualTo(Integer value) {
            addCriterion("id_parcial <>", value, "id_parcial");
            return (Criteria) this;
        }

        public Criteria andId_parcialGreaterThan(Integer value) {
            addCriterion("id_parcial >", value, "id_parcial");
            return (Criteria) this;
        }

        public Criteria andId_parcialGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_parcial >=", value, "id_parcial");
            return (Criteria) this;
        }

        public Criteria andId_parcialLessThan(Integer value) {
            addCriterion("id_parcial <", value, "id_parcial");
            return (Criteria) this;
        }

        public Criteria andId_parcialLessThanOrEqualTo(Integer value) {
            addCriterion("id_parcial <=", value, "id_parcial");
            return (Criteria) this;
        }

        public Criteria andId_parcialIn(List<Integer> values) {
            addCriterion("id_parcial in", values, "id_parcial");
            return (Criteria) this;
        }

        public Criteria andId_parcialNotIn(List<Integer> values) {
            addCriterion("id_parcial not in", values, "id_parcial");
            return (Criteria) this;
        }

        public Criteria andId_parcialBetween(Integer value1, Integer value2) {
            addCriterion("id_parcial between", value1, value2, "id_parcial");
            return (Criteria) this;
        }

        public Criteria andId_parcialNotBetween(Integer value1, Integer value2) {
            addCriterion("id_parcial not between", value1, value2, "id_parcial");
            return (Criteria) this;
        }

        public Criteria andId_CarreraIsNull() {
            addCriterion("id_Carrera is null");
            return (Criteria) this;
        }

        public Criteria andId_CarreraIsNotNull() {
            addCriterion("id_Carrera is not null");
            return (Criteria) this;
        }

        public Criteria andId_CarreraEqualTo(Integer value) {
            addCriterion("id_Carrera =", value, "id_Carrera");
            return (Criteria) this;
        }

        public Criteria andId_CarreraNotEqualTo(Integer value) {
            addCriterion("id_Carrera <>", value, "id_Carrera");
            return (Criteria) this;
        }

        public Criteria andId_CarreraGreaterThan(Integer value) {
            addCriterion("id_Carrera >", value, "id_Carrera");
            return (Criteria) this;
        }

        public Criteria andId_CarreraGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_Carrera >=", value, "id_Carrera");
            return (Criteria) this;
        }

        public Criteria andId_CarreraLessThan(Integer value) {
            addCriterion("id_Carrera <", value, "id_Carrera");
            return (Criteria) this;
        }

        public Criteria andId_CarreraLessThanOrEqualTo(Integer value) {
            addCriterion("id_Carrera <=", value, "id_Carrera");
            return (Criteria) this;
        }

        public Criteria andId_CarreraIn(List<Integer> values) {
            addCriterion("id_Carrera in", values, "id_Carrera");
            return (Criteria) this;
        }

        public Criteria andId_CarreraNotIn(List<Integer> values) {
            addCriterion("id_Carrera not in", values, "id_Carrera");
            return (Criteria) this;
        }

        public Criteria andId_CarreraBetween(Integer value1, Integer value2) {
            addCriterion("id_Carrera between", value1, value2, "id_Carrera");
            return (Criteria) this;
        }

        public Criteria andId_CarreraNotBetween(Integer value1, Integer value2) {
            addCriterion("id_Carrera not between", value1, value2, "id_Carrera");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table examen
     *
     * @mbggenerated do_not_delete_during_merge Thu May 26 13:30:53 CDT 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}