package com.escom.schoolsaes.model;

import java.util.Date;

public class Parcial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parcial.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parcial.fecha_inicio
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Date fecha_inicio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parcial.fecha_fin
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Date fecha_fin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parcial.id
     *
     * @return the value of parcial.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parcial.id
     *
     * @param id the value for parcial.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parcial.fecha_inicio
     *
     * @return the value of parcial.fecha_inicio
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Date getFecha_inicio() {
        return fecha_inicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parcial.fecha_inicio
     *
     * @param fecha_inicio the value for parcial.fecha_inicio
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setFecha_inicio(Date fecha_inicio) {
        this.fecha_inicio = fecha_inicio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parcial.fecha_fin
     *
     * @return the value of parcial.fecha_fin
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Date getFecha_fin() {
        return fecha_fin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parcial.fecha_fin
     *
     * @param fecha_fin the value for parcial.fecha_fin
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setFecha_fin(Date fecha_fin) {
        this.fecha_fin = fecha_fin;
    }
}