package com.escom.schoolsaes.model;

public class PreguntaExamenRespuesta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pregunta_examen_respuesta.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pregunta_examen_respuesta.id_pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id_pregunta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pregunta_examen_respuesta.id_respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id_respuesta;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pregunta_examen_respuesta.id_examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    private Integer id_examen;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pregunta_examen_respuesta.id
     *
     * @return the value of pregunta_examen_respuesta.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pregunta_examen_respuesta.id
     *
     * @param id the value for pregunta_examen_respuesta.id
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pregunta_examen_respuesta.id_pregunta
     *
     * @return the value of pregunta_examen_respuesta.id_pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId_pregunta() {
        return id_pregunta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pregunta_examen_respuesta.id_pregunta
     *
     * @param id_pregunta the value for pregunta_examen_respuesta.id_pregunta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId_pregunta(Integer id_pregunta) {
        this.id_pregunta = id_pregunta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pregunta_examen_respuesta.id_respuesta
     *
     * @return the value of pregunta_examen_respuesta.id_respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId_respuesta() {
        return id_respuesta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pregunta_examen_respuesta.id_respuesta
     *
     * @param id_respuesta the value for pregunta_examen_respuesta.id_respuesta
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId_respuesta(Integer id_respuesta) {
        this.id_respuesta = id_respuesta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pregunta_examen_respuesta.id_examen
     *
     * @return the value of pregunta_examen_respuesta.id_examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public Integer getId_examen() {
        return id_examen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pregunta_examen_respuesta.id_examen
     *
     * @param id_examen the value for pregunta_examen_respuesta.id_examen
     *
     * @mbggenerated Thu May 26 13:30:53 CDT 2016
     */
    public void setId_examen(Integer id_examen) {
        this.id_examen = id_examen;
    }
}